version: '3.8'

services:
  db:
    image: postgres:14
    container_name: shared_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - shared_db_data:/var/lib/postgresql/data
      - ./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql

  api_produtos:
    build: ./product-registration
    container_name: api_products
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/produtos_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "8081:8080"
    depends_on:
      - db

  api_clientes:
    build: ./customer-management
    container_name: api_customers
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/clientes_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "8082:8080"
    depends_on:
      - db

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: petshop_identity
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak_db
      - KC_DB_USERNAME=${POSTGRES_USER:-postgres}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  shared_db_data:
    driver: local