apiVersion: v1
kind: Secret
metadata:
  name: api-produtos-secret
type: Opaque
data:
  # Valores obrigatoriamente em Base64
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM=