apiVersion: v1
kind: Service
metadata:
  name: api-produtos-svc
spec:
  type: NodePort
  selector:
    app: api-produtos
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081 # A porta que você usará no localhost (ex: localhost:30081)