apiVersion: v1
kind: Secret
metadata:
  name: db-produtos-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM=
